### ISSUE TITLE
Can we publish this plugin in wordpress.org?

### ISSUE THREAD

**Issue by lucas-viewup** [adomasalcore3/Advanced-Custom-Fields-Google-Maps-Extended#3]
Hello, @adomasalcore3, can we publish or mantain the plugin in wordpress.org since we are not the owners of plugin, only mantainers?

Regards,

**Comment by tlcd96** [comment]
the plugin isn't mine too, i've just modified to allow to put the google map api key.

**Comment by tlcd96** [comment]
but since the author, doesn't care about it, you can publish it.

**Comment by tlcd96** [comment]
also i've addered you to collaborators
